XamarinFun/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace XamarinFun.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {

            return View();
        }

        public IActionResult MyMobileApps()
        {

            return View("MyMobileApps");
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

XamarinFun/Controllers/PrivacyPolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace XamarinFun.Controllers
{
    public class PrivacyPolicyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

XamarinFun/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

    <h2>@ViewData["Title"].</h2>
    Xamarin Fun is my website that helps promote development with Xamarin because it is great!

XamarinFun/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Mobile Apps";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

XamarinFun/Views/Home/Index.cshtml
    <h2>Home Page</h2>
    "We created Xamarin because we knew there had to be a better way to build mobile apps. We’re developers, so we know what developers want: a modern programming language, powerful tools, an efficient and delightful workflow and the power to create the best user experiences. We are on a mission to make it fast, easy and fun to build great mobile apps."
    <a href="https://www.xamarin.com/about">-Retrieved here</a>

XamarinFun/Views/Home/MyMobileApps.cshtml
@{
    ViewData["Title"] = "My Mobile Apps";
}

<div class="row">
    <div class="col-lg-12">
        <h2>@ViewData["Title"]</h2>
        <h3>@ViewData["Message"]</h3>
    </div>
    <div class="col-lg-12">
        <h3> Android Apps:</h3>
        <ul>
            <li><a href="https://play.google.com/store/apps/details?id=com.magetech.newedh">EDH Life</a></li>
            <li><a href="https://play.google.com/store/apps/details?id=com.magetech.fwn">Free Word Note</a></li>
        </ul>
       <h3>Android Games:</h3>
        <ul>
            <li><a href="https://play.google.com/store/apps/details?id=com.Magetech.Newfalling">Falling Man</a></li>
        </ul>
        
    </div>

    <div class="col-lg-12">
        <h3>Apple Apps:</h3>
        <ul>
            <li><a href="https://itunes.apple.com/us/app/edh-life/id1193005762?ls=1&mt=8">EDH Life</a></li>
        </ul>
        <h3>Apple Games:</h3>
        <ul>
            <li><a href="https://itunes.apple.com/us/app/magetechfallingman/id1369639117?ls=1&mt=8">Magetech Falling Man</a></li>
        </ul>
    </div>
</div>

XamarinFun/Views/PrivacyPolicy/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<div class="row">
    <h2>Privacy Policy for all of my Xamarin Applications</h2>
</div>
<div class="row">
    <p>This Privacy Policy governs the manner in which XamarinFun collects, uses, maintains and discloses information collected from users (each, a "User") of the http://xamarinfun.azurewebsites.net website ("Site").</p>
</div>
<div class="row">
    <p>
        Personal identification information
        We may collect personal identification information from Users in a variety of ways in connection with activities, services, features or resources we make available on our Site. Users may visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.
    </p>
</div>
<div class="row">
    <p>
        Non-personal identification information
        We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.
    </p>
</div>
<div class="row">
    <p>


        Web browser cookies
        Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.
    </p>
</div>
<div class="row">
    <p>
        How we use collected information
        XamarinFun may collect and use Users personal information for the following purposes:
    </p>
</div>
<div class="row">
    <p>
        To run and operate our Site
        We may need your information display content on the Site correctly.
        How we protect your information
        We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.
    </p>
</div>
<div class="row">
    <p>
        Sharing your personal information
        We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.
    </p>
</div>
<div class="row">
    <p>
        We may share or sell information with third parties for marketing or other purposes.
    </p>
</div>
<div class="row">
    <p>
        Sharing your personal information
        This Privacy Policy governs the manner in which XamarinFun collects, uses, maintains and discloses information collected from users (each, a "User") of the http://XamarinFun.azurewebsites.net website ("Site").
    </p>
</div>
<div class="row">
    <p>
        Personal identification information
        We may collect personal identification information from Users in a variety of ways in connection with activities, services, features or resources we make available on our Site. Users may visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.
    </p>
</div>
<div class="row">
    <p>
        Non-personal identification information
        We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.
    </p>
</div>
<div class="row">
    <p>
        Web browser cookies
        Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.
    </p>
</div>
<div class="row">
    <p>
        How we use collected information
        XamarinFun may collect and use Users personal information for the following purposes:
    </p>
</div>
<div class="row">
    <p>
        To run and operate our Site
        We may need your information display content on the Site correctly.
        How we protect your information
        We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.
    </p>
</div>
<div class="row">
    <p>
        Sharing your personal information
        We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.
    </p>
</div>
<div class="row">
    <p>
        We may share or sell information with third parties for marketing or other purposes.
    </p>
</div>
<div class="row">
    <p>
        Changes to this privacy policy
        XamarinFun has the discretion to update this privacy policy at any time. When we do, we will post a notification on the main page of our Site. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.
    </p>
</div>
<div class="row">
    <p>
        Your acceptance of these terms
        By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes. This policy was generated using Privacy Policies.com
    </p>
</div>
<div class="row">
    <p>
        Contacting us
        If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us.
    </p>
</div>
<div class="row">
    <p>
        This document was last updated on January 08, 2017
    </p>
</div>
<div class="row">

</div>

XamarinFun/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XamarinFun</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">XamarinFun</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="MyMobileApps">My Mobile Apps</a></li>
                    <li><a asp-area="" asp-controller="PrivacyPolicy" asp-action="Index">Privacy Policy</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - XamarinFun</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>